# Using a Public API with Python

In [1]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import pandas as pd

In [2]:
url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '8839d3f8-4bce-45ac-8059-c9c329c395c1',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)


# To run: jupyter notebook --NotebookApp.iopub_data_rate_limit=1e10
# Gives the local:
# http://localhost:8889/?token=3683b264983dd64cbee16a39830773756134364fcd001a8f

In [3]:
type (data)

dict

In [4]:
#This allows you to see all the columns, not just like 15
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

#This normalizes the data and makes it all pretty in a dataframe
pd.json_normalize(data['data'])

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,10938,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.965965e+07,19659650,False,NaN,1,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,6.400545e+04,6.291235e+10,-8.1337,0.670769,2.473458,-11.868260,22.801644,54.216534,45.902312,1.258325e+12,52.2044,1.344114e+12,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,8610,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.200757e+08,1.20076e+08,True,NaN,2,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,3.343952e+03,3.161932e+10,1.2563,-0.263470,3.843950,-16.146696,15.389720,35.851627,49.405403,4.015272e+11,16.6615,4.015272e+11,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,79608,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,1.037795e+11,1.07793e+11,True,NaN,3,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,9.998915e-01,1.147903e+11,-11.9013,0.020119,0.063812,-0.067742,-0.010915,0.053770,-0.017106,1.037683e+11,4.3059,1.077811e+11,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,2113,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.495379e+08,1.49538e+08,False,NaN,4,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,5.275855e+02,3.077295e+09,-33.1301,-0.726224,3.353475,-10.190079,50.132163,68.401950,93.852002,7.889401e+10,3.2715,7.889401e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN
4,5426,Solana,SOL,solana,643,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.439976e+08,5.72295e+08,True,NaN,5,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,1.731612e+02,8.599763e+09,-28.2135,0.172880,-2.483766,13.656148,53.417709,89.790906,100.424325,7.688316e+10,3.1903,9.909937e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,19182,Gametree,GTCOIN,gametree,2,2022-03-30T04:37:09.000Z,[ethereum-ecosystem],1.000000e+10,0.000000e+00,10000000000,False,NaN,4996,3.205897e+09,2.054317e+06,NaN,2024-03-20T14:24:00.000Z,6.407933e-04,1.615635e+04,27.9227,0.135930,-0.340572,-12.430682,-40.678217,-57.106072,-69.954279,0.000000e+00,0.0000,6.407933e+06,NaN,2024-03-20T14:24:00.000Z,4256.0,Klaytn,KLAY,klaytn,0xa17a000e0c251b429ca0485e1d0d4503881e7bb6
4996,16285,Triathon,GEON,triathon,3,2021-12-20T10:33:50.000Z,[],1.000000e+10,0.000000e+00,1500000000,False,NaN,4997,1.500000e+09,3.897799e+06,NaN,2024-03-20T14:24:00.000Z,2.598533e-03,1.613326e+04,342.2997,-0.868679,-6.102134,-29.085905,-45.097534,0.631674,128.992887,0.000000e+00,0.0000,2.598533e+07,NaN,2024-03-20T14:24:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x167FcFED3AAD2d11052fCde0cbf704D879939473
4997,28291,Apu,APU,apu-token,3,2023-10-26T13:26:38.000Z,[memes],4.200000e+11,0.000000e+00,420000000000,False,NaN,4998,4.200000e+11,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,3.211184e-07,1.607626e+04,-84.5852,-0.669928,-15.435728,-2.759526,529.654630,352.528768,229.852768,0.000000e+00,0.0000,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0x0b5a91a43cb798c45fd56bfb5d41c13c42a7afa8
4998,26160,Toshe,TOSHE,go-bnb,3,2024-01-08T12:55:00.000Z,[],1.200000e+14,0.000000e+00,108972083377464,False,NaN,4999,1.089721e+14,4.936991e+05,NaN,2024-03-20T14:24:00.000Z,4.530510e-09,1.604371e+04,113.2857,1.144611,0.985896,-15.673650,-24.802798,43.679893,3215.310491,0.000000e+00,0.0000,5.436612e+05,NaN,2024-03-20T14:24:00.000Z,27716.0,Base,TBA,base,0x00E57Ec29EF2bA7dF07Ad10573011647B2366f6D
4999,20615,Fatih Karagümrük SK Fan Token,FKSK,fatih-karagumruk-sk-fan-token,3,2022-06-14T15:13:37.000Z,[fan-token],NaN,0.000000e+00,0,False,NaN,5000,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,7.605912e-04,1.603467e+04,-4.8030,-0.453924,-7.919248,-9.562259,-22.361572,-20.092182,-39.923218,0.000000e+00,0.0000,0.000000e+00,NaN,2024-03-20T14:25:00.000Z,8357.0,Bitcichain,BITCI,bitcicoin,0x4a7521236ea97d99346d17deeb0fe13fcef2cb83

In [5]:
#This normalizes the data and makes it all pretty in a dataframe

df = pd.json_normalize(data['data'])

df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,10938,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.965965e+07,19659650,False,NaN,1,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,6.400545e+04,6.291235e+10,-8.1337,0.670769,2.473458,-11.868260,22.801644,54.216534,45.902312,1.258325e+12,52.2044,1.344114e+12,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,8610,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.200757e+08,1.20076e+08,True,NaN,2,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,3.343952e+03,3.161932e+10,1.2563,-0.263470,3.843950,-16.146696,15.389720,35.851627,49.405403,4.015272e+11,16.6615,4.015272e+11,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,79608,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,1.037795e+11,1.07793e+11,True,NaN,3,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,9.998915e-01,1.147903e+11,-11.9013,0.020119,0.063812,-0.067742,-0.010915,0.053770,-0.017106,1.037683e+11,4.3059,1.077811e+11,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,2113,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.495379e+08,1.49538e+08,False,NaN,4,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,5.275855e+02,3.077295e+09,-33.1301,-0.726224,3.353475,-10.190079,50.132163,68.401950,93.852002,7.889401e+10,3.2715,7.889401e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN
4,5426,Solana,SOL,solana,643,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.439976e+08,5.72295e+08,True,NaN,5,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,1.731612e+02,8.599763e+09,-28.2135,0.172880,-2.483766,13.656148,53.417709,89.790906,100.424325,7.688316e+10,3.1903,9.909937e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,19182,Gametree,GTCOIN,gametree,2,2022-03-30T04:37:09.000Z,[ethereum-ecosystem],1.000000e+10,0.000000e+00,10000000000,False,NaN,4996,3.205897e+09,2.054317e+06,NaN,2024-03-20T14:24:00.000Z,6.407933e-04,1.615635e+04,27.9227,0.135930,-0.340572,-12.430682,-40.678217,-57.106072,-69.954279,0.000000e+00,0.0000,6.407933e+06,NaN,2024-03-20T14:24:00.000Z,4256.0,Klaytn,KLAY,klaytn,0xa17a000e0c251b429ca0485e1d0d4503881e7bb6
4996,16285,Triathon,GEON,triathon,3,2021-12-20T10:33:50.000Z,[],1.000000e+10,0.000000e+00,1500000000,False,NaN,4997,1.500000e+09,3.897799e+06,NaN,2024-03-20T14:24:00.000Z,2.598533e-03,1.613326e+04,342.2997,-0.868679,-6.102134,-29.085905,-45.097534,0.631674,128.992887,0.000000e+00,0.0000,2.598533e+07,NaN,2024-03-20T14:24:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x167FcFED3AAD2d11052fCde0cbf704D879939473
4997,28291,Apu,APU,apu-token,3,2023-10-26T13:26:38.000Z,[memes],4.200000e+11,0.000000e+00,420000000000,False,NaN,4998,4.200000e+11,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,3.211184e-07,1.607626e+04,-84.5852,-0.669928,-15.435728,-2.759526,529.654630,352.528768,229.852768,0.000000e+00,0.0000,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0x0b5a91a43cb798c45fd56bfb5d41c13c42a7afa8
4998,26160,Toshe,TOSHE,go-bnb,3,2024-01-08T12:55:00.000Z,[],1.200000e+14,0.000000e+00,108972083377464,False,NaN,4999,1.089721e+14,4.936991e+05,NaN,2024-03-20T14:24:00.000Z,4.530510e-09,1.604371e+04,113.2857,1.144611,0.985896,-15.673650,-24.802798,43.679893,3215.310491,0.000000e+00,0.0000,5.436612e+05,NaN,2024-03-20T14:24:00.000Z,27716.0,Base,TBA,base,0x00E57Ec29EF2bA7dF07Ad10573011647B2366f6D
4999,20615,Fatih Karagümrük SK Fan Token,FKSK,fatih-karagumruk-sk-fan-token,3,2022-06-14T15:13:37.000Z,[fan-token],NaN,0.000000e+00,0,False,NaN,5000,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,7.605912e-04,1.603467e+04,-4.8030,-0.453924,-7.919248,-9.562259,-22.361572,-20.092182,-39.923218,0.000000e+00,0.0000,0.000000e+00,NaN,2024-03-20T14:25:00.000Z,8357.0,Bitcichain,BITCI,bitcicoin,0x4a7521236ea97d99346d17deeb0fe13fcef2cb83

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  5000 non-null   int64
 1   name                                5000 non-null   object
 2   symbol                              5000 non-null   object
 3   slug                                5000 non-null   object
 4   num_market_pairs                    5000 non-null   int64
 5   date_added                          5000 non-null   object
 6   tags                                5000 non-null   object
 7   max_supply                          3549 non-null   float64
 8   circulating_supply                  5000 non-null   float64
 9   total_supply                        5000 non-null   object
 10  infinite_supply                     5000 non-null   bool
 11  platform                            0 non-null      float64
 12  cmc_rank                            5000 non-null   int64
 13  self_reported_circulating_supply    3217 non-null   float64
 14  self_reported_market_cap            3217 non-null   float64
 15  tvl_ratio                           78 non-null     float64
 16  last_updated                        5000 non-null   object
 17  quote.USD.price                     5000 non-null   float64
 18  quote.USD.volume_24h                5000 non-null   float64
 19  quote.USD.volume_change_24h         5000 non-null   float64
 20  quote.USD.percent_change_1h         5000 non-null   float64
 21  quote.USD.percent_change_24h        5000 non-null   float64
 22  quote.USD.percent_change_7d         5000 non-null   float64
 23  quote.USD.percent_change_30d        5000 non-null   float64
 24  quote.USD.percent_change_60d        5000 non-null   float64
 25  quote.USD.percent_change_90d        5000 non-null   float64
 26  quote.USD.market_cap                5000 non-null   float64
 27  quote.USD.market_cap_dominance      5000 non-null   float64
 28  quote.USD.fully_diluted_market_cap  5000 non-null   float64
 29  quote.USD.tvl                       83 non-null     float64
 30  quote.USD.last_updated              5000 non-null   object
 31  platform.id                         4288 non-null   float64
 32  platform.name                       4288 non-null   object
 33  platform.symbol                     4288 non-null   object
 34  platform.slug                       4288 non-null   object
 35  platform.token_address              4288 non-null   object
dtypes: bool(1), float64(20), int64(3), object(12)
memory usage: 1.3+ MB

In [7]:
# This reates "timestamp"

df['timestamp'] = pd.to_datetime('now')  #the time now
df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,10938,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.965965e+07,19659650,False,NaN,1,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,6.400545e+04,6.291235e+10,-8.1337,0.670769,2.473458,-11.868260,22.801644,54.216534,45.902312,1.258325e+12,52.2044,1.344114e+12,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788
1,1027,Ethereum,ETH,ethereum,8610,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.200757e+08,1.20076e+08,True,NaN,2,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,3.343952e+03,3.161932e+10,1.2563,-0.263470,3.843950,-16.146696,15.389720,35.851627,49.405403,4.015272e+11,16.6615,4.015272e+11,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788
2,825,Tether USDt,USDT,tether,79608,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,1.037795e+11,1.07793e+11,True,NaN,3,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,9.998915e-01,1.147903e+11,-11.9013,0.020119,0.063812,-0.067742,-0.010915,0.053770,-0.017106,1.037683e+11,4.3059,1.077811e+11,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2024-03-20 14:26:25.647788
3,1839,BNB,BNB,bnb,2113,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.495379e+08,1.49538e+08,False,NaN,4,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,5.275855e+02,3.077295e+09,-33.1301,-0.726224,3.353475,-10.190079,50.132163,68.401950,93.852002,7.889401e+10,3.2715,7.889401e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788
4,5426,Solana,SOL,solana,643,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.439976e+08,5.72295e+08,True,NaN,5,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,1.731612e+02,8.599763e+09,-28.2135,0.172880,-2.483766,13.656148,53.417709,89.790906,100.424325,7.688316e+10,3.1903,9.909937e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,19182,Gametree,GTCOIN,gametree,2,2022-03-30T04:37:09.000Z,[ethereum-ecosystem],1.000000e+10,0.000000e+00,10000000000,False,NaN,4996,3.205897e+09,2.054317e+06,NaN,2024-03-20T14:24:00.000Z,6.407933e-04,1.615635e+04,27.9227,0.135930,-0.340572,-12.430682,-40.678217,-57.106072,-69.954279,0.000000e+00,0.0000,6.407933e+06,NaN,2024-03-20T14:24:00.000Z,4256.0,Klaytn,KLAY,klaytn,0xa17a000e0c251b429ca0485e1d0d4503881e7bb6,2024-03-20 14:26:25.647788
4996,16285,Triathon,GEON,triathon,3,2021-12-20T10:33:50.000Z,[],1.000000e+10,0.000000e+00,1500000000,False,NaN,4997,1.500000e+09,3.897799e+06,NaN,2024-03-20T14:24:00.000Z,2.598533e-03,1.613326e+04,342.2997,-0.868679,-6.102134,-29.085905,-45.097534,0.631674,128.992887,0.000000e+00,0.0000,2.598533e+07,NaN,2024-03-20T14:24:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0x167FcFED3AAD2d11052fCde0cbf704D879939473,2024-03-20 14:26:25.647788
4997,28291,Apu,APU,apu-token,3,2023-10-26T13:26:38.000Z,[memes],4.200000e+11,0.000000e+00,420000000000,False,NaN,4998,4.200000e+11,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,3.211184e-07,1.607626e+04,-84.5852,-0.669928,-15.435728,-2.759526,529.654630,352.528768,229.852768,0.000000e+00,0.0000,1.348697e+05,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0x0b5a91a43cb798c45fd56bfb5d41c13c42a7afa8,2024-03-20 14:26:25.647788
4998,26160,Toshe,TOSHE,go-bnb,3,2024-01-08T12:55:00.000Z,[],1.200000e+14,0.000000e+00,108972083377464,False,NaN,4999,1.089721e+14,4.936991e+05,NaN,2024-03-20T14:24:00.000Z,4.530510e-09,1.604371e+04,113.2857,1.144611,0.985896,-15.673650,-24.802798,43.679893,3215.310491,0.000000e+00,0.0000,5.436612e+05,NaN,2024-03-20T14:24:00.000Z,27716.0,Base,TBA,base,0x00E57Ec29EF2bA7dF07Ad10573011647B2366f6D,2024-03-20 14:26:25.647788
4999,20615,Fatih Karagümrük SK Fan Token,FKSK,fatih-karagumruk-sk-fan-token,3,2022-06-14T15:13:37.000Z,[fan-token],NaN,0.000000e+00,0,False,NaN,5000,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,7.605912e-04,1.603467e+04,-4.8030,-0.453924,-7.919248,-9.562259,-22.361572,-20.092182,-39.923218,0.000000e+00,0.0000,0.000000e+00,NaN,2024-03-20T14:25:00.000Z,8357.0,Bitcichain,BITCI,bitcicoin,0x4a7521236ea97d99346d17deeb0fe13fcef2cb83,2024-03-20 14:26:25.647788

In [8]:
# Save table as csv
df.to_csv("data/CoinMarketCap.csv", index = False)

## Second Fase

In [9]:
def api_runner():
    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
    
    parameters = {
      'start':'1',
      'limit':'15',
      'convert':'USD'
    }
    headers = {
      'Accepts': 'application/json',
      'X-CMC_PRO_API_KEY': '8839d3f8-4bce-45ac-8059-c9c329c395c1',
    }

    session = Session()
    session.headers.update(headers)

    try:
      response = session.get(url, params=parameters)
      data = json.loads(response.text)
      #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
      print(e)
    
    # Use this if you just want to keep it in a dataframe
    df2 = pd.json_normalize(data['data'])
    df2['Timestamp'] = pd.to_datetime('now')
    df = df.append(df2)


    # Use this if you want to create a csv and append data to it
    #df = pd.json_normalize(data['data'])
    #df['timestamp'] = pd.to_datetime('now')
    #df

    #if not os.path.isfile(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv'):
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', header='column_names')
    #else:
        #df.to_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv', mode='a', header=False)
        
    #Then to read in the file: df = pd.read_csv(r'C:\Users\alexf\OneDrive\Documents\Python Scripts\API.csv')

In [10]:
import os 
from time import time
from time import sleep

for i in range(3):
    api_runner()
    print('API Runner completed')
    sleep(10) #sleep 60 = 1 minute
exit()

API Runner completed
API Runner completed
API Runner completed

In [11]:
# Save table as csv

df.to_csv("data/CoinMarketCapDin.csv", index = False)

df

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp,Timestamp
0,1,Bitcoin,BTC,bitcoin,10938,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.965965e+07,19659650,False,NaN,1,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,64005.447751,6.291235e+10,-8.1337,0.670769,2.473458,-11.868260,22.801644,54.216534,45.902312,1.258325e+12,52.2044,1.344114e+12,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788,NaT
1,1027,Ethereum,ETH,ethereum,8610,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.200757e+08,1.20076e+08,True,NaN,2,NaN,NaN,NaN,2024-03-20T14:25:00.000Z,3343.951586,3.161932e+10,1.2563,-0.263470,3.843950,-16.146696,15.389720,35.851627,49.405403,4.015272e+11,16.6615,4.015272e+11,NaN,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788,NaT
2,825,Tether USDt,USDT,tether,79608,2015-02-25T00:00:00.000Z,"[payments, stablecoin, asset-backed-stablecoin...",NaN,1.037795e+11,1.07793e+11,True,NaN,3,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,0.999891,1.147903e+11,-11.9013,0.020119,0.063812,-0.067742,-0.010915,0.053770,-0.017106,1.037683e+11,4.3059,1.077811e+11,NaN,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2024-03-20 14:26:25.647788,NaT
3,1839,BNB,BNB,bnb,2113,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.495379e+08,1.49538e+08,False,NaN,4,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,527.585475,3.077295e+09,-33.1301,-0.726224,3.353475,-10.190079,50.132163,68.401950,93.852002,7.889401e+10,3.2715,7.889401e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788,NaT
4,5426,Solana,SOL,solana,643,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.439976e+08,5.72295e+08,True,NaN,5,NaN,NaN,NaN,2024-03-20T14:24:00.000Z,173.161223,8.599763e+09,-28.2135,0.172880,-2.483766,13.656148,53.417709,89.790906,100.424325,7.688316e+10,3.1903,9.909937e+10,NaN,2024-03-20T14:24:00.000Z,NaN,NaN,NaN,NaN,NaN,2024-03-20 14:26:25.647788,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,5994,Shiba Inu,SHIB,shiba-inu,771,2020-08-01T00:00:00.000Z,"[memes, ethereum-ecosystem, doggone-doggerel]",NaN,5.892894e+14,5.89534e+14,False,NaN,11,NaN,NaN,None,2024-03-20T14:24:00.000Z,0.000026,1.657265e+09,-4.8812,0.078174,2.290271,-19.676050,163.315346,172.267635,148.757535,1.508482e+10,0.6255,1.509109e+10,None,2024-03-20T14:24:00.000Z,1027.0,Ethereum,ETH,ethereum,0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce,NaT,2024-03-20 14:26:46.619389
11,11419,Toncoin,TON,toncoin,231,2021-08-26T13:40:22.000Z,"[pos, layer-1, ftx-bankruptcy-estate, dwf-labs...",NaN,3.469133e+09,5.10446e+09,True,NaN,12,3.414167e+09,1.402080e+10,None,2024-03-20T14:26:00.000Z,4.106654,1.841922e+08,-4.1653,-1.078599,9.892170,-9.075141,82.356140,84.801431,76.373231,1.424653e+10,0.5908,2.096226e+10,None,2024-03-20T14:26:00.000Z,NaN,NaN,NaN,NaN,NaN,NaT,2024-03-20 14:26:46.619389
12,6636,Polkadot,DOT,polkadot-new,721,2020-08-19T00:00:00.000Z,"[substrate, polkadot, binance-chain, polkadot-...",NaN,1.424159e+09,1.42416e+09,True,NaN,13,NaN,NaN,None,2024-03-20T14:25:00.000Z,9.102940,4.778794e+08,-16.1444,-0.741976,1.501136,-15.852917,18.555303,33.538368,18.883952,1.296403e+10,0.5376,1.296403e+10,None,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,NaT,2024-03-20 14:26:46.619389
13,1975,Chainlink,LINK,chainlink,1700,2017-09-20T00:00:00.000Z,"[platform, defi, oracles, smart-contracts, sub...",1.000000e+09,5.871000e+08,1e+09,False,NaN,14,NaN,NaN,None,2024-03-20T14:25:00.000Z,17.560789,7.135361e+08,-21.0010,0.315849,0.852834,-14.196810,-11.079478,11.063534,18.071589,1.030994e+10,0.4273,1.756079e+10,None,2024-03-20T14:25:00.000Z,1027.0,Ethereum,ETH,ethereum,0x514910771af9ca656af840dff83e8264ecf986ca,NaT,2024-03-20 14:26:46.619389
14,1958,TRON,TRX,tron,957,2017-09-13T00:00:00.000Z,"[media, payments, tron-ecosystem, layer-1, dwf...",NaN,8.781556e+10,8.78156e+10,True,NaN,15,7.165966e+10,8.398291e+09,None,2024-03-20T14:25:00.000Z,0.117197,6.391047e+08,3.2704,-0.062251,1.882773,-10.912700,-13.700896,6.636669,12.554445,1.029171e+10,0.4271,1.029172e+10,None,2024-03-20T14:25:00.000Z,NaN,NaN,NaN,NaN,NaN,NaT,2024-03-20 14:26:46.619389

In [12]:
# One thing I noticed was the scientific notation. I like it, but I want to be able to see the numbers in this case

pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [13]:
# Now let's look at the coin trends over time

df3 = df.groupby('name', sort=False)[['quote.USD.percent_change_1h','quote.USD.percent_change_24h',
                                      'quote.USD.percent_change_7d','quote.USD.percent_change_30d',
                                      'quote.USD.percent_change_60d','quote.USD.percent_change_90d']].mean()
df3

,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d
name,,,,,,
Bitcoin,0.64936,2.25515,-11.81635,22.90696,54.18706,45.85483
Ethereum,-0.25898,3.66392,-16.08629,15.49840,35.86559,49.46925
Tether USDt,0.02012,0.06381,-0.06774,-0.01091,0.05377,-0.01711
BNB,-0.54978,3.58967,-10.17366,50.25722,68.53118,93.99779
Solana,0.17288,-2.48377,13.65615,53.41771,89.79091,100.42432
...,...,...,...,...,...,...
Gametree,0.13593,-0.34057,-12.43068,-40.67822,-57.10607,-69.95428
Triathon,-0.86868,-6.10213,-29.08590,-45.09753,0.63167,128.99289
Apu,-0.66993,-15.43573,-2.75953,529.65463,352.52877,229.85277
Toshe,1.14461,0.98590,-15.67365,-24.80280,43.67989,3215.31049
Fatih Karagümrük SK Fan Token,-0.45392,-7.91925,-9.56226,-22.36157,-20.09218,-39.92322

In [14]:
df4 = df3.stack()
df4

name
Bitcoin                        quote.USD.percent_change_1h      0.64936
                               quote.USD.percent_change_24h     2.25515
                               quote.USD.percent_change_7d    -11.81635
                               quote.USD.percent_change_30d    22.90696
                               quote.USD.percent_change_60d    54.18706
                                                                 ...
Fatih Karagümrük SK Fan Token  quote.USD.percent_change_24h    -7.91925
                               quote.USD.percent_change_7d     -9.56226
                               quote.USD.percent_change_30d   -22.36157
                               quote.USD.percent_change_60d   -20.09218
                               quote.USD.percent_change_90d   -39.92322
Length: 29766, dtype: float64

In [15]:
type(df4)

pandas.core.series.Series

In [16]:
df5 = df4.to_frame(name='values')
df5

                                                              values
name
Bitcoin                       quote.USD.percent_change_1h    0.64936
                              quote.USD.percent_change_24h   2.25515
                              quote.USD.percent_change_7d  -11.81635
                              quote.USD.percent_change_30d  22.90696
                              quote.USD.percent_change_60d  54.18706
...                                                              ...
Fatih Karagümrük SK Fan Token quote.USD.percent_change_24h  -7.91925
                              quote.USD.percent_change_7d   -9.56226
                              quote.USD.percent_change_30d -22.36157
                              quote.USD.percent_change_60d -20.09218
                              quote.USD.percent_change_90d -39.92322

[29766 rows x 1 columns]

In [17]:
df5.count()

values    29766
dtype: int64

In [18]:
#Because of how it's structured above we need to set an index. I don't want to pass a column as an index for this dataframe
#So I'm going to create a range and pass that as the dataframe. You can make this more dynamic, but I'm just going to hard 
#code it


index = pd.Index(range(29766))

# Set the above DataFrame index object as the index
# using set_index() function
df6 = df5.reset_index()
df6

# If it only has the index and values try doing reset_index like "df5.reset_index()"

                                name                       level_1    values
0                            Bitcoin   quote.USD.percent_change_1h   0.64936
1                            Bitcoin  quote.USD.percent_change_24h   2.25515
2                            Bitcoin   quote.USD.percent_change_7d -11.81635
3                            Bitcoin  quote.USD.percent_change_30d  22.90696
4                            Bitcoin  quote.USD.percent_change_60d  54.18706
...                              ...                           ...       ...
29761  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_24h  -7.91925
29762  Fatih Karagümrük SK Fan Token   quote.USD.percent_change_7d  -9.56226
29763  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_30d -22.36157
29764  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_60d -20.09218
29765  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_90d -39.92322

[29766 rows x 3 columns]

In [19]:
# Change the column name

df7 = df6.rename(columns={'level_1': 'percent_change'})
df7

                                name                percent_change    values
0                            Bitcoin   quote.USD.percent_change_1h   0.64936
1                            Bitcoin  quote.USD.percent_change_24h   2.25515
2                            Bitcoin   quote.USD.percent_change_7d -11.81635
3                            Bitcoin  quote.USD.percent_change_30d  22.90696
4                            Bitcoin  quote.USD.percent_change_60d  54.18706
...                              ...                           ...       ...
29761  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_24h  -7.91925
29762  Fatih Karagümrük SK Fan Token   quote.USD.percent_change_7d  -9.56226
29763  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_30d -22.36157
29764  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_60d -20.09218
29765  Fatih Karagümrük SK Fan Token  quote.USD.percent_change_90d -39.92322

[29766 rows x 3 columns]

In [20]:
df7['percent_change'] = df7['percent_change'].replace(['quote.USD.percent_change_24h','quote.USD.percent_change_7d',
                                                       'quote.USD.percent_change_30d','quote.USD.percent_change_60d',
                                                       'quote.USD.percent_change_90d'],['24h','7d','30d','60d','90d'])
df7

                                name               percent_change    values
0                            Bitcoin  quote.USD.percent_change_1h   0.64936
1                            Bitcoin                          24h   2.25515
2                            Bitcoin                           7d -11.81635
3                            Bitcoin                          30d  22.90696
4                            Bitcoin                          60d  54.18706
...                              ...                          ...       ...
29761  Fatih Karagümrük SK Fan Token                          24h  -7.91925
29762  Fatih Karagümrük SK Fan Token                           7d  -9.56226
29763  Fatih Karagümrük SK Fan Token                          30d -22.36157
29764  Fatih Karagümrük SK Fan Token                          60d -20.09218
29765  Fatih Karagümrük SK Fan Token                          90d -39.92322

[29766 rows x 3 columns]